sonar.projectKey=Sharqascc_nnds
sonar.organization=sharqascc
sonar.projectName=nnds
sonar.sources=src,paper/analysis
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/node_modules/**
sonar.coverage.exclusions=paper/analysis/**/*.py
